kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: kube-netcheck
  namespace: kube-system
  labels:
    app: kube-netcheck
spec:
  selector:
    matchLabels:
      app: kube-netcheck
  template:
    metadata:
      labels:
        app: kube-netcheck
    spec:
      tolerations:
        # Allow the pod to run on the master.  This is required for
        # the master to communicate with pods.
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: kube-netcheck
          image: quay.io/giantswarm/kube-netcheck:latest
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 50Mi
          livenessProbe:
            httpGet:
              path: /
              port: 6666